version: '3.9'


volumes:
  acmesky_db_data:
    driver: local
  airline_db_data:
    driver: local

services:
    acmesky_db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: pg
            POSTGRES_PASSWORD: pass 
            POSTGRES_HOST: acmesky_db 
            POSTGRES_DB: acmesky 
        ports:
            - "5432:5432"
        volumes:
          - ./src/ACMESky/ACMESkyDB/init.sql:/docker-entrypoint-initdb.d/init.sql
          - acmesky_db_data:/var/lib/postgresql

    acmesky_frontend:
        build: ./src/ACMESky/ACMESkyWeb/frontend
        ports:
            - "8080:80"

    acmesky_backend:
        build: ./src/ACMESky/ACMESkyWeb/backend
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: production
        depends_on:
            - acmesky_db

    camunda_acmesky:
        image: camunda/camunda-bpm-platform:latest
        container_name: camunda_acmesky
        ports: 
            - 10000:8080
            - 9990:9990
        
    camunda_workers:
        build: ./src/ACMESky/camunda
        container_name: camunda_workers
        env_file: ./src/ACMESky/camunda/.env
        environment:
            - PYTHONHASHSEED=1
        depends_on:
            - acmesky_db

    airline_service:
        build: ./src/airlineService
        env_file: ./src/airlineService/.env
        ports:
            - 8085:8085
        command: sh -c "sleep 5 && ./main"
        restart: always
        depends_on:
          - airline_db

    airline_db:
        image: postgres:latest
        restart: always
        env_file: ./src/airlineService/.env
        ports:
          - "5433:5432"
        volumes:
          - ./src/airlineService/data.sql:/docker-entrypoint-initdb.d/data.sql
          - airline_db_data:/var/lib/postgresql

    bank_frontend:
        build: ./src/bankService/frontend/
        ports:
            - "8087:8087"

    bank_backend:
        build: ./src/bankService/backend/
        ports:
            - "3001:3001"
        environment:
            NODE_ENV: production
            
    prontogram_frontend:
        build: ./src/prontogram/frontend
        ports:
            - "8089:8089"
        restart: always
    # prontogram_backend:
    #     container_name: prontogram_service_container
    #     build: ./src/Prontogram/back-end
    #     ports:
    #         - "8050:8000"
    #     restart: always
    #     networks: 
    #         - acmesky

    rent_service_1:
        build: ./src/rentService
        environment:
            - SERVICE_NAME=RentService1
        ports:
            - "8030:8030"
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        restart: always
        # networks: 
        #     - acmesky
    rent_service_2:
        build: ./src/rentService
        environment:
            - SERVICE_NAME=RentService2
        ports:
            - "8032:8032"
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        restart: always
        # networks: 
        #     - acmesky

    geodistance:
        container_name: geodistance_container
        build: ./src/geodistanceService
        env_file:
            - ./src/geodistanceService/.env
        ports:
            - "8040:8040"
        restart: always
        # networks: 
        #     - acmesky
