export const BASE_URL = "http://localhost:3000"
export const BASE_AIRLINE_URL = "http://localhost:8085"
export const BASE_URL_BANK = "http://localhost:3001"
export const BASE_URL_GEO = "http://localhost:8040"
export const BASE_URL_SSE = "http://localhost:3002"