version: 3

services:
    rent-service-1:
        container_name: rent_service_1
        build: ./
        environment:
            - SERVICE_NAME=RentService1
        ports:
            - "9091:9090"
        restart: always
        # networks: 
        #     - acmesky

    rent-service-2:
        container_name: rent_service_2
        build: ./
        environment:
            - SERVICE_NAME=RentService2
        ports:
            - "9092:9090"
        restart: always
        # networks: 
        #     - acmesky


# networks:
#     acmesky:
#         external: true
#         name: acmesky-net
