version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c "sleep 5 && ./main"
    networks: 
      - acmesky
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - db:/var/lib/postgresql/data
    networks: 
      - acmesky

volumes:
  db:

networks:
    acmesky:
        external: true
        name: acmesky-net
